### ISSUE TITLE
Add interactive runme TUX mode

### ISSUE THREAD

**Issue by sourishkrout** [stateful/runme#100]
It would be awesome if when you run the bare "runme" command it would drop you into an interactive list with each command section and you could run it by hitting enter and then use the arrows keys to switch to the next section.

So the CLI interactions would be:

 1. runme
 2. <enter> to run first section
 3. <down-arrow> to select next item
 4. <enter> to run the second section

**Comment by sourishkrout** [comment]
Implemented by https://github.com/stateful/runme/pull/103

**Comment by sourishkrout** [comment]
Just shipped with v0.5.0. Cc @silas, sorry about the delay - we had a company offsite in the middle of it.

**Comment by silas** [comment]
Awesome, just updated, thanks everyone!
