### ISSUE TITLE
internal/runner: `curl`'ing image hangs `readLoop`

### ISSUE THREAD

**Issue by mxsdev** [stateful/runme#143]
I wrote the following test (in `Test_runnerService`) which results in `readLoop` hanging. This runs one of the scripts in the official `README.md`.

```golang
	t.Run("ExecuteCurl", func(t *testing.T) {
		t.Parallel()

		stream, err := client.Execute(context.Background())
		require.NoError(t, err)

		execResult := make(chan executeResult)
		go getExecuteResult(stream, execResult)

		err = stream.Send(&runnerv1.ExecuteRequest{
			ProgramName: "bash",
			Script:      "curl https://lever-client-logos.s3.us-west-2.amazonaws.com/a8ff9b1f-f313-4632-b90f-1f7ae7ee807f-1638388150933.png 2>/dev/null",
		})
		assert.NoError(t, err)

		result := <-execResult

		assert.Len(t, result.Responses, 1)
	})
```

**Comment by adambabik** [comment]
Which version of runme did you test it against? I tried it with a slightly modified script value and it works as expected on the current main branch:

```go
	t.Run("ExecuteCurl", func(t *testing.T) {
		t.Parallel()

		stream, err := client.Execute(context.Background())
		require.NoError(t, err)

		execResult := make(chan executeResult)
		go getExecuteResult(stream, execResult)

		err = stream.Send(&runnerv1.ExecuteRequest{
			ProgramName: "bash",
			Script:      "curl -s https://lever-client-logos.s3.us-west-2.amazonaws.com/a8ff9b1f-f313-4632-b90f-1f7ae7ee807f-1638388150933.png >/dev/null",
		})
		assert.NoError(t, err)

		result := <-execResult

		require.NoError(t, result.Err)
		require.NotEmpty(t, result.Responses)
		assert.EqualValues(t, 0, result.Responses[len(result.Responses)-1].ExitCode.Value)
	})
```

**Comment by adambabik** [comment]
After digging deeper into this with @mxsdev, we discovered that the root cause of this is the overflowing `RingBuffer` which `Read()` method goes into infinite loop.

Additionally, we decided that replacing `RingBuffer` with a variable-sized buffer with a maximum size might be a better choice. 

One more alternative is using `io.Pipe()` that has no buffering. It might produce other issues, though.

**Comment by adambabik** [comment]
The issue with the `RingBuffer` is described in https://github.com/stateful/runme/issues/149.
