### ISSUE TITLE
internal/runner: `readEnvFromFile` cannot parse env variables with new lines

### ISSUE THREAD

**Issue by mxsdev** [stateful/runme#154]
The function `readEnvFromFile` naively parses on new-lines, which of course will not support environment variables containing new lines. This is causing truncation for multiline environment variables, for example.

For now I guess we can use the `env -0` flag to separate by null terminators, instead of new lines.

In the future, though, we probably should properly (JSON)-encode environment variables. I imagine this can be wrapped up as part of #148 - probably we could expose a subcommand of `runme` to wrap around something like `godotenv`, which handles marshaling/parsing.

**Comment by adambabik** [comment]
> In the future, though, we probably should properly (JSON)-encode environment variables.

At some point you need to parse the output of `env` so `-0` seems like a good choice to do that reliably. If you don't need it to be portable, you can use https://pkg.go.dev/encoding/gob instead of JSON.

**Comment by mxsdev** [comment]
> At some point you need to parse the output of env so -0 seems like a good choice to do that reliably.

It's better than new lines, but it sort of just moves the issue from new lines to null characters. So before you couldn't have new lines in your envs, now you can't have null characters in your envs. Ideally, envs can be anything.

> If you don't need it to be portable, you can use https://pkg.go.dev/encoding/gob instead of JSON.

Yup I think that's a good choice. Especially since this is all non-persisted, we can always change the way its encoded later without issue 👍

**Comment by adambabik** [comment]
> It's better than new lines, but it sort of just moves the issue from new lines to null characters. So before you couldn't have new lines in your envs, now you can't have null characters in your envs. Ideally, envs can be anything.

I don't think you can have null byes in env values. That's why that option is available to have a reliable separator.

**Comment by mxsdev** [comment]
> I don't think you can have null byes in env values. That's why that option is available to have a reliable separator.

Ah, that makes sense. We're good then ✨
