### ISSUE TITLE
internal/runner: Implement LRU/"AutoSession" mechanism

### ISSUE THREAD

**Issue by mxsdev** [stateful/runme#176]
It would be nice to have an "auto session" mechanism, particularly for the `run` command. 

Basically, the gRPC server would just hold a pointer to the most recently used session, and when this proto flag (maybe called `AutoSession`) is provided on an initial request, it will use this session, or create a new one if there is none.

This does potentially create a security concern, because a potential attacker can now get access to a session and all of it's variables without needing to know it's session ID.

**Comment by mxsdev** [comment]
@sourishkrout thoughts?

**Comment by sourishkrout** [comment]
> @sourishkrout thoughts?

Agreed, we should start with something simple. Like you suggested, any security concerns can be mitigated by *not* making it default behavior yet.
