### ISSUE TITLE
Feature Request: export to clipboard

### ISSUE THREAD

**Issue by mikeage** [stateful/runme#195]
I don't know if this is possible in Windows, but for Linux (using `xclip`) and Mac (using `pbcopy`) it'd be nice if we could export a section to the clipboard. For cases where the command requires interactive use (e.g., an embedded ssh command), it's easier to run the commands in a separate shell. If there was an option from the main menu to copy to the system's clipboard, this would be very useful (using `<space>` to expand and then selecting is my current workflow)

**Comment by christian-bromann** [comment]
Thanks for raising the issue @mikeage 

To make sure I understood your request, what do you exactly mean with "export a section"? Runme [already has a copy button](https://runme.dev/docs/features#copy--paste) to copy a code cell or its results into clipboard. How should we extend this functionality to better serve your use case?

> For cases where the command requires interactive use (e.g., an embedded ssh command), it's easier to run the commands in a separate shell.

I am very curious if you could describe an example workflow/command?

**Comment by mikeage** [comment]
export was probably a bad word.

The copy button is exactly what I'm looking for... except for the command line version. I don't use vscode or the notebooks.

**Comment by christian-bromann** [comment]
@mikeage gotcha, thanks for clarifying!

@mxsdev @sourishkrout I would suggest the following interface:

- to copy command cells from markdown files, introduce a `copy` command that can take the id of the command cell, prints it to stdout and adds a message e.g. "Copied to Clipboard!"
- if no id was provided, e.g. `runme copy` it would automatically copy the stdout/stderr from the last run command, if no command was run, throw an error (this also means runme has to store stdout/err from commands in a temporary file to access it in this scenario)

Wdyt?

**Comment by mxsdev** [comment]
I think adding a copy functionality to the TUI is no problem - just made #196 if you think that would suit your needs @mikeage 

As for a dedicated copy command, yeah that interface works. Though it might be a little weird having the command have the functionality of copying stdout when nothing is provided - probably it's better UX to give a list of options, and copy on selection.

**Comment by christian-bromann** [comment]
> Though it might be a little weird having the command have the functionality of copying stdout when nothing is provided

What do you mean by this? Given the two scenarios I mentioned:

- `runme copy idOfCell`: here I would assume the cell is not empty, but if so, we can print an info message saying that it is and nothing was copied
- `runme copy` same here, in case the previous command didn't create we can provide an info message and fallback doing a NOOP

**Comment by mikeage** [comment]
Just tried it-- exactly what I wanted!

**Comment by mxsdev** [comment]
> What do you mean by this? ... [further description]

Hmm, yeah I see what you're saying. I guess for me I would assume that `runme copy` would provide a list of possible options for copying. But that is just me, and I can see where you're coming from. I'd like to get @sourishkrout 's thoughts as well for sure. But honestly whether it's default behavior or behind some flag, is small details.

In any case, it is an interesting feature. Copying stdout would be pretty reasonable for the TUI since it maintains the session. There are security concerns of course about storing stdout on disk somewhere, but it can be done reasonably I think.

**Comment by sourishkrout** [comment]
@mikeage closing this as completed in https://github.com/stateful/runme/pull/196. Let us know please if have overlooked anything.

**Comment by mikeage** [comment]
Thanks again!
