### ISSUE TITLE
Using . $ % as descriptions for branch suggest end up with an error. 

### ISSUE THREAD

**Issue by duvanmonsa** [stateful/runme#222]
Using descriptions like this `test $ @ here` will throw ` Internal server error`

![image](https://user-images.githubusercontent.com/2709271/233433189-de7c58a5-4501-44a7-b271-aec501e55243.png)

**Comment by sourishkrout** [comment]
@duvanmonsa false alarm, right? Can we close this?

**Comment by duvanmonsa** [comment]
@sourishkrout yes that's correct closing this issue.

**Comment by duvanmonsa** [comment]
@sourishkrout maybe we can consider changing this and displaying a better message to users if they do not have admin permissions, or do you think we would just remove that logic whenever we get everything in place with GTO credentials?

**Comment by sourishkrout** [comment]
> @sourishkrout maybe we can consider changing this and displaying a better message to users if they do not have admin permissions, or do you think we would just remove that logic whenever we get everything in place with GTO credentials?

we'll remove the `site_admin` requirement for public release, that's just temporary. No need to more polish here yet.
