### ISSUE TITLE
Stdin sometimes improperly suppressed from output

### ISSUE THREAD

**Issue by sourishkrout** [stateful/runme#223]
Inside a Codespaces workspace, I can't see to reflect anything entered (non-secret stuff) inside of the terminal:

Inside notebook terminal:
![Apr-21-2023 11-18-31](https://user-images.githubusercontent.com/250527/233673745-4ea5d8ff-f31b-4311-a8f8-c13bb4e23088.gif)

Integrated terminal:
<img width="977" alt="image" src="https://user-images.githubusercontent.com/250527/233673729-6ad291b2-0c4f-43a9-8bcd-a89770eaebce.png">

**Comment by mxsdev** [comment]
I am investigating this now.

I am able to reproduce on macos as well, so I don't think this is linux-specific. I have edited the issue title as such, feel free to change it back if you disagree!

**Comment by sourishkrout** [comment]
All good :+1:. Thank you.
