### ISSUE TITLE
Not all tokens are being saved per env

### ISSUE THREAD

**Issue by sourishkrout** [stateful/runme#228]
When auth-ing the CLI against staging it overwrites the `github.json` which is also being used for production.

Should the CLI write different files per env?

**Comment by duvanmonsa** [comment]
@sourishkrout Currently we save a config file per environment to store the `runme` token and we reuse the GitHub token for all of them because in the end that makes sense it can be the same and we shouldn't have problems with that.  did you have a problem using the same token for staging and prod?

**Comment by sourishkrout** [comment]
> @sourishkrout Currently we save a config file per environment to store the `runme` token and we reuse the GitHub token for all of them because in the end that makes sense it can be the same and we shouldn't have problems with that. did you have a problem using the same token for staging and prod?

Ah right 🤦‍♀️. My bad. I logged into different accounts. That was the issue not different env. All good. Thanks @duvanmonsa!
