### ISSUE TITLE
Multiple tasks and parallelism in `runme run`

### ISSUE THREAD

**Issue by sourishkrout** [stateful/runme#229]
In a discreet PR let's make it possible to run multiple commands optionally sequential and parallel available.

The rough idea is `runme run one two three -p four five six -s seven eight nine` (please note the presence of `runme run` as a subcommand for now).

**Comment by sourishkrout** [comment]
cc @mxsdev. In the meantime, I will review the other suggested concepts, including relaxing the file-centricity @christian-bromann.

**Comment by mxsdev** [comment]
@christian-bromann 

For implementation I think we should introduce two new functions which take the `Runner` interface  (`internal/runner/client/client.go`). Probably the most idiomatic way to do this is to introduce a struct, let's call it `MultiRunner`, which encapsulates some internal runner(s), and then to define methods on that. You create a multirunner by passing a `[]RunnerOption` list, and each command run gets its own `Runner` instance.

The first function will be `RunBlocksSerial`. The implementation here is straight-forward: run each command one after the other, and exit if one of these commands fails.

The second function will be `RunBlocksParallel`. This implementation is less straight forward. Each call to `RunBlock` should have its own context and run in its own goroutine. We can use a `WaitGroup` here to wait for all goroutines to finish, and you'll also need to introduce a channel to pipe command results if you want to summarize them at the end. 

It will also be absolutely critical that each execution has it's own stdin and stdout objects. You can accomplish this by connecting an `io.Pipe()` to the assigned stdout, stderr, and stdin. (This also gives us the opportunity to prefix each stdout line with the associated command's name, if we so wish) 

You will also have to modify the `Runner` interface to allow "transformation" of the stdin/out objects - some method like `WithTransformStdout` which passes the current stdout and assigns the result would be a nice functional way of doing this in a way compatible with the `RunnerOption` paradigm. Then for each runner, you can create a new pipe and push/pull the necessary changes through that pipe, and all that logic could happen in the transform callback.

As for the command parsing, it would be very nice to keep manual parsing to an absolute minimum, ideally with everything being handled by [cobra](https://pkg.go.dev/github.com/spf13/cobra). I don't personally know all the limits of that library, but I implore you to read as much of the docs as possible before resorting to manual parsing.

I also anticipate some very complicated issues regarding stdin. You'll need to modify the current behavior of the runner clients in such a way that the multirunner cancels the stdin not once a single command finishes, but after they all finish.
