### ISSUE TITLE
Automatically source ENV vars in .env

### ISSUE THREAD

**Issue by mxsdev** [stateful/runme#234]
Part of moving from single file to project model.

Might make sense as part of vscode-runme rather than runme.

**Comment by eshepelyuk** [comment]
Hello

I'd like to reopen the issues, since env vars loading is not working when used with `--filename` flag.

1. Runme version
```sh
runme --version
runme version 3.9.4 (Homebrew) on 2024-11-21T22:49:56Z
```

1. Env file
```sh
cat .env
export MY_VAR=SOME_VALUE
```

1. Runme playbook
```sh
cat test.runme
# header

```sh {"name":"env"}
echo "@@${MY_VAR}@@"
```

1. Invoking `runme run`,with `--filename` doesn't read the variables from `.env`
```sh
runme run --all -y --filename='test.runme'
@@@@
```

1. Although `runme run` without `--filename` works OK
```sh
runme run --all -y
@@SOME_VALUE@@
```
