### ISSUE TITLE
Parse frontmatter to enable document-scope configuration + shell configuration

### ISSUE THREAD

**Issue by sourishkrout** [stateful/runme#249]
Runme currently retains frontmatter opaquely like a blob. It does not attempt to parse it.

Let's add support for yaml/json frontmatter. Toml is a nice-to-have which we could add later.

Similar to the fenced code block annotations, we want to add a configuration option allowing users to set a shell, such as `/bin/bash` instead of defaulting to the system's.

**Comment by mxsdev** [comment]
This is really two separate issues, the former of which is covered in #88.
