### ISSUE TITLE
Support tick annotations

### ISSUE THREAD

**Issue by christian-bromann** [stateful/runme#25]
It would be great if users could add additional information to the code block which then can be parsed and send along, e.g.:

    ```html type="svelte"
    ...
    ```

For the CLI we could use this for filtering certain blocks and for using `rdme` as wasm file this could be helpful to annotate important information about the code block.

**Comment by adambabik** [comment]
It is already supported but in a bit different format:

    ```html {type=svelte}
    ...
    ```

However, you can't do match about it. Only the language is recognized (`html` in this example) which is used to select an executor in the CLI, and `name`.

We can return them in the JSON renderer, though.

**Comment by christian-bromann** [comment]
Yep, didn't know about. Maybe something we can document?

**Comment by adambabik** [comment]
It is mentioned in https://github.com/stateful/runme/blob/main/examples/README.md but also covered in https://www.runme.dev/docs/annotations.
