### ISSUE TITLE
Unintentional frontmatter changes when editing notebooks

### ISSUE THREAD

**Issue by christian-bromann** [stateful/runme#251]
I just added a Runme notebook ([source]() and got the following changes:

```patch
-    ```sh
-    git clone <url>
-    ```
+```sh { attachments=[object Object] }
+git clone <url>
+```
+
 5. Run the following command to specify a new remote upstream repository that will be synced with the fork:

-    ```sh
-    git remote add upstream git@github.com:great-expectations/great_expectations.git
-    ```
+```sh { attachments=[object Object] }
+git remote add upstream git@github.com:great-expectations/great_expectations.git
+```
+
 6. Run the following command to create a branch for your changes:

-    ```sh
-    git checkout -b <branch-name>
-    ```
+```sh { attachments=[object Object] }
+git checkout -b <branch-name>
+```
```

I am not sure what `attachments` are but it seems that setting it to `[object Object]` seems not intentional.

**Comment by sourishkrout** [comment]
Any chance you dragged and dropped a file? I read in the VS Code release notes that handlers were added for dropping files. Maybe we have to "handle" that now?

**Comment by christian-bromann** [comment]
> Any chance you dragged and dropped a file?

Not intentionally.

**Comment by sourishkrout** [comment]
OK. But, do you remember dragging and dropping something? Any other hints how to reproduce the issue would be much appreciated.

**Comment by joseeantonior** [comment]
Considering we don't still have steps to reproduce this, I'll go ahead and close it. If we can reproduce it, we'll re-open.
