### ISSUE TITLE
Allow to kill process through `CTRL` + `c`

### ISSUE THREAD

**Issue by christian-bromann** [stateful/runme#257]
If you kick off a Runme command and try to kill it via `CTRL` + `c` it won't have any effect. It would be great if users can cancel a runme task at any time.

**Comment by mxsdev** [comment]
Are you having this issue in interactive scripts? It should work fine in those. 

Non-interactive scripts don't process `Ctrl + c` though.

**Comment by christian-bromann** [comment]
I am running runme in the terminal and once it runs multiple commands, it doesn't seem to be able to quit, e.g.:

    # Contributing

    Run all this:

    ```sh { name=runme }
    runme --project . run taskA taskB taskC
    ```

    ```sh { name=taskA }
    sleep 2
    ```
    ```sh { name=taskB }
    sleep 4
    ```
    ```sh { name=taskC }
    sleep 6
    ```

With above example , pressing CTRL + c during execution of `taskA` works but not anymore after `taskB` has kicked off.
