### ISSUE TITLE
Can't find command

### ISSUE THREAD

**Issue by christian-bromann** [stateful/runme#258]
For some reasons Runme is not able to find my `test` command even though it is clearly defined and visible when calling the `list` command:

![Screenshot 2023-05-22 at 14 00 50](https://github.com/stateful/runme/assets/731337/180a9f5a-988a-4460-a500-b1247312a7fc)

**Comment by sourishkrout** [comment]
Do you have a link with a branch/repo, please, @christian-bromann?

**Comment by sourishkrout** [comment]
It's likely because names such as `test:depcheck` are invalid when treated as regex. I wonder if we should treat them as regular strings unless a flag is specified. I believe sed/grep use `-e` to turn on regex. Wdyt, @mxsdev?

**Comment by mxsdev** [comment]
@sourishkrout 

Currently investigating, in the image provided it should definitely find the script named "test"

**Comment by christian-bromann** [comment]
Could this be resolved through grouping? I've seen that there is a parameter to run from a specific category but couldn't find much information/docs around it. I wouldn't mind just adding a group frontmatter to achieve the same.

**Comment by christian-bromann** [comment]
> it should definitely find the script named "test"

I think it does but has issues executing the first command which is `test:depcheck`. Note that `test` is defined as follows:

    ```sh { name=test }
    $ npx runme --project . run test;depcheck test:linting test:typings test:unit test:smoke test:component test:e2e
    ```

**Comment by sourishkrout** [comment]
> @sourishkrout
> 
> Currently investigating, in the image provided it should definitely find the script named "test"

It does find "test", however, it'll recursively call `runme`, please see the cell definition which fails due to the colons.

**Comment by sourishkrout** [comment]
> Could this be resolved through grouping? I've seen that there is a parameter to run from a specific category but couldn't find much information/docs around it. I wouldn't mind just adding a group frontmatter to achieve the same.

Yes, that's what the groups are meant for. Once they are ready.

**Comment by mxsdev** [comment]
> It does find "test", however, it'll recursively call runme, please see the cell definition which fails due to the colons.

Ah, I see

In this case, the reason this is happening is because we decided on colon for our separator. So `runme run test:depcheck` interprets the "test" prefix as a query on the file system, and looks for a script named "depcheck" instead.

Maybe we should switch to `/` as a separator? Alternatively we can introduce a new flag for specifying a file.

**Comment by sourishkrout** [comment]
> > It does find "test", however, it'll recursively call runme, please see the cell definition which fails due to the colons.
> 
> Ah, I see
> 
> In this case, the reason this is happening is because we decided on colon for our separator. So `runme run test:depcheck` interprets the "test" prefix as a query on the file system, and looks for a script named "depcheck" instead.
> 
> I originally thought this would be fine since I thought the extension strips special characters from script names, but I may have been wrong there. And people interface with readmes in many ways anyway.
> 
> Maybe we should switch to `/` as a separator? Alternatively we can introduce a new flag for specifying a file.

Ah! let's switch to `/` for now.

I think we want to diligence this use case more and can make changes as we go as long as it's opt-in.

**Comment by christian-bromann** [comment]
To add some context on this: I've been using [`npm-run-all`](https://www.npmjs.com/package/npm-run-all) where it is possible to say:

```sh
npm-run-all foobar:*
```

which executes all commands prefixed with `foobar:` starting with the one that is defined first in `package.json` and ending with the one that is define last. See an example in the current [`package.json`](https://github.com/webdriverio/webdriverio/blob/main/package.json) of the WebdriverIO project. It would be nice if Runme could behave similar to that.

**Comment by mxsdev** [comment]
@christian-bromann 

Only reason something like this wasn't implemented is since I'm not sure which query language to use here. Regexp I think would require `foobar\:.*` which isn't great, and glob would be `foobar:**`. Another problem with glob is that is requires full strings, rather than matching on substrings.

Feel free to make a separate issue on that one for "partial command matching."

**Comment by sourishkrout** [comment]
I think it's important to just "get it working" even if some things seem unnecessary verbose or suboptimal. We can then start working backward from a working solution.
