### ISSUE TITLE
Cannot join Discord channel

### ISSUE THREAD

**Issue by fbartels** [stateful/runme#277]
Hi,
I played a bit around with your project the last few days and wanted to join the Discord channel. Looking at the website and this repo I am finding two links (with different sized channels apparently), but both do no longer work:

- https://discord.com/invite/runme
- https://discord.com/invite/MFtwcSvJsk

**Comment by admc** [comment]
Hi Felix, can you try https://discord.gg/runme

Thanks for reporting this.

Adam

**Comment by admc** [comment]
@fbartels i've updated both those links to use the .gg link and goto the right place, please let me know if you have any more issues. We'd love to have you join us in Discord!

**Comment by fbartels** [comment]
Thanks for the updated links. Originally it did not work when trying to join from my desktop. But when i later tried from my mobile they did.

I have now joined the discord
