### ISSUE TITLE
Configurable CLI options just for running code in the open terminal 

### ISSUE THREAD

**Issue by alexandrupetrini** [stateful/runme#296]
Hi, 

Love the extension, looks nice :smiley: !

What I really need is a way to run (paste + run code) in an open terminal, as I use TMUX heavily and it would be hard to open a mutli-session restored tmux, switch to specific session, window, pane etc. 

Desperately need, hardly do I find :smile: !

Thanks!

**Comment by sourishkrout** [comment]
hey @alexandrupetrini 👋 ! thanks for your ticket. So `paste + run code` would go from a cell into the active tmux-based terminal? Just so I understand this right.

**Comment by alexandrupetrini** [comment]
Hi @sourishkrout,

All I can say for sure is that "zvik.command-runner" extension does this:

![2023-06-14_19-11](https://github.com/stateful/runme/assets/44755709/3d8e5df7-cf71-4664-8b48-657722b4d1c9)

It's similar to Copy/Paste into the terminal whereever the cursor is, and Run.

But here is the actual code: 
```ts
  static run(command: string) {
    Terminal._term().sendText(command, true);
  }
 ```
from: https://github.com/zvikarp/command-runner/blob/master/src/Terminal.ts

I also have this extension installed, but it forces me to go back to the text editor, in order to use it
