### ISSUE TITLE
Disable CLI prompts

### ISSUE THREAD

**Issue by christian-bromann** [stateful/runme#297]
With #253 we introduced a feature that would enable the CLI to prompt the user for environment variables. However there are situations where this is not desired:

- if the environment variable is already set
- in CI
- if I like the env to be empty

I would suggest to make this behavior optional and only have the CLI prompt use if the user opts in.
Wdyt?

**Comment by duvanmonsa** [comment]
@christian-bromann Thank you for reporting I think it makes sense, we can set that feature off by default and add a new flag `--prompt-envs` would love to hear @mxsdev and @sourishkrout

**Comment by sourishkrout** [comment]
How about skipping prompts when no tty is attached? Provide a flag to overwrite it (force prompting)?

**Comment by mxsdev** [comment]
I agree with the three cases Christian provided:

> if the environment variable is already set
> in CI
> if I like the env to be empty

I already thought we had a flag - we should definitely add one.

> I would suggest to make this behavior optional and only have the CLI prompt use if the user opts in.

This breaks parity with behavior in the extension.

> How about skipping prompts when no tty is attached? Provide a flag to overwrite it (force prompting)?

Yeah, we should definitely not ask for a env prompt in CI

**Comment by sourishkrout** [comment]
Let's create a solution where we have a 1.) flag to force skipping as well as 2.) a detection whether or not a TTY is attached and, if not, auto-skip, @duvanmonsa.

**Comment by sourishkrout** [comment]
Done (https://github.com/stateful/runme/pull/359) and released.
