### ISSUE TITLE
Rename rdme to runme. Be careful about the distribution channels.

### ISSUE THREAD

**Issue by sourishkrout** [stateful/runme#30]
If there is a deprecation mechanism it'd be great to transition everyone to `runme`. However, distributing them in parallel is fine too.

Let's also rename the public repo.

**Comment by adambabik** [comment]
@sourishkrout The plan looks like this:
1. Rename everything to runme, including download links `https://download.stateful.com/runme/{{ .Version }}/{{ .ArtifactName }}`, URLs in manifests and documentation, etc. to https://runme.dev.
2. Change the repo name.
3. For Homebrew, add an alias `rdme` in https://github.com/stateful/homebrew-tap for backward compatibility. For Scoop I haven't found such functionality. We can do one more final release of rdme that will check if the binary is run as `rdme` or `runme`. In the former case, we can print a warning that the name has changed and link to https://runme.dev.

**Comment by sourishkrout** [comment]
I think it'd be fine to just rename scoop. Don't think we'll break a ton of users.
