### ISSUE TITLE
Add examples to README

### ISSUE THREAD

**Issue by vitonsky** [stateful/runme#304]
Hi, your project looks interesting. I suggest you to add more information to README file. It is important for developers while research solutions on intertent to see features as soon as possible, to good project will not be skipped.

- [ ] Add markdown file with example and explain short how it works
- [ ] Add a section "How it works" with technical details for 2-3 sentences

Ideal README file do not force users to read docs site to got what this project about and how it works.
Try to keep this README structure:

- Short description with 1 paragraph
- Most important details with few sentences for 1-3 paragraph
- Section how to use (and how to build if necessary)
- Section with examples
- Additional sections like "how to contribute"

**Comment by christian-bromann** [comment]
@vitonsky raised a PR in #306, let me know what you think!
