### ISSUE TITLE
Feature request: Use closest header as default name

### ISSUE THREAD

**Issue by peterbraden** [stateful/runme#348]
Right now when you run `runme` in a repository, you are likely to get: `no named code blocks, consider adding flag --allow-unnamed` as a response, as most people haven't tagged their code blocks by default.

An alternative would be to traverse the markdown tree and use the closest 'heading' as a decent fallback for the name.

For example:

```markdown

# Run my thing
` ` ` sh
$ echo "Hello World"
` ` `

```

Could use the name 'run-my-thing' for the code block.

**Comment by sourishkrout** [comment]
Thanks @peterbraden! We'll take a look into the suggestion.

Fairly close to getting https://github.com/stateful/runme/pull/341 merged, which will consider all blocks if not a single named block is available, amongst other improvements.

We will circle back.

**Comment by sourishkrout** [comment]
Done as per previous comment.
