### ISSUE TITLE
non-interactive mode for whole document

### ISSUE THREAD

**Issue by ruzickap** [stateful/runme#349]
Hello guys.

Would be possible to introduce the new CLI parameter `--non-interactive` which will together with `runme run --all` execute all commands without any interaction (like standard script)? 

This may be handy for testing the whole document in pipeline.

Thank you...

**Comment by sourishkrout** [comment]
Thanks for raising this @ruzickap. We do have a similar ticket here: https://github.com/stateful/runme/issues/297. We'll take a look.

**Comment by sourishkrout** [comment]
This was fixed and released in https://github.com/stateful/runme/issues/297#issuecomment-1675113228.

The way it will work is adding `--skip-prompts` to explicitly force it. However, in a C/I pipeline it will auto-detect whether or not a terminal is attached and default to `--skip-prompts=false`, @ruzickap. Let us know how it goes for you.
