### ISSUE TITLE
Feature Request: Document-level options "category" 

### ISSUE THREAD

**Issue by ruzickap** [stateful/runme#369]
Hello guys.

I have a following use case where I would like to use the document-level option - category.

```text
.
├── install-manual-solution-1.md
├── install-manual-solution-2.md
└── install-manual-solution-3.md
```

In each of the file - I have a description, how to install some solution which contains the installation steps/commands.

My suggestion is to set the document level `category` option which will allow me to run the commands  inside specific file as category.

For example:

* `install-manual-solution-1.md`
<pre>
---
shell: bash
cwd: /tmp
category: solution-1
---

Installation steps for Solution 1:

```sh
echo "Install command in $PWD"
``` 

```sh { category=delete-solution }
echo "Delete solution"
```
</pre>

* `install-manual-solution-2.md`
<pre>
---
shell: bash
cwd: /tmp
category: solution-2
---

Installation steps for Solution 2:

```sh
echo "Install command in $PWD"
``` 

```sh { category=delete-solution }
echo "Delete solution"
``` 
</pre>

Then I would like to call `runme run --all --skip-prompts --category solution-2` to install "solution-2" by execution commands in code blocks inside the md file which doesn't have explicitly defined `category` cell option.

---

Currently I can achieve the same behavior as mentioned above in case I will define category for all code blocks like:

<pre>
```sh { category=solution-??? }
...
```
</pre>

Obviously repeating the `category=solution-???` for each code block in files is something I would like to avoid because it is a lot of repetitions...

Thank you...

**Comment by christian-bromann** [comment]
@ruzickap thanks for filing the issue.

With the example you provided above:

````md
---
shell: bash
cwd: /tmp
category: solution-1
---

Installation steps for Solution 1:

```sh
echo "Install command in $PWD"
``` 

```sh { category=delete-solution }
echo "Delete solution"
```
````

Do you expect that the cell with the content `echo "Delete solution"` has two categories, `solution-1` and `delete-solution` or just the one applied to the cell directly?

**Comment by ruzickap** [comment]
Actually none of these.

If you explicitly define the category in code block (like it is for the `category=delete-solution` below) it should have precedence and "overwrite" the document-level `category` option.

For example:

<pre>
---
shell: bash
cwd: /tmp
category: solution-1
---

Installation steps for Solution 1:

```sh
echo "Install Solution 1 commands (create database)"
```

```sh
echo "Install Solution 1 commands (create server)"
```


```sh { category=delete-solution-1 }
echo "Delete solution 1 commands (delete server)"
```

```sh { category=delete-solution-1 }
echo "Delete solution 1 commands (delete database)"
```

</pre>

Then I can call:
* Create/Install Solution 1: `runme run --all --skip-prompts --category solution-1`
* Delete Solution 1: `runme run --all --skip-prompts --category delete-solution-1`
* CI/CD test (create+destroy) Solution 1: `runme run --all --skip-prompts --category solution-1,delete-solution-1`

This will help me to have all the details (create/delete procedure) about "Solution 1" in one document and run create / delete parts easily if needed.

It should also allow me to run the "tests" - where I would like to create and destroy "Solution 1" in one pipeline/batch: `runme run --all --skip-prompts --category solution-1,delete-solution-1`

What is your opinion?

**Comment by christian-bromann** [comment]
I would agree with you. The way you've outlined gives most flexibility.

**Comment by pastuxso** [comment]
Hello @ruzickap, thank you for requesting this feature. It's already included in the latest version of Runme. Please let us know if it's working as you expect, and I'll be sure to stay tuned.

**Comment by ruzickap** [comment]
Thank you for developing this feature :-)

Actually, it seems like there is some bug.

Example - let's have the following file:

* `install-manual-solution-2.md`
<pre>
---
shell: bash
cwd: /tmp
category: solution-2
---

Installation steps for Solution 2:

```sh
echo "[1] Install command in $PWD"
```

```sh
echo "[2] Install second command"
```

```sh { "category":"delete-solution" }
echo "Delete solution"
```

```sh { "category":"delete-solution" }
echo "Delete solution - second command"
```
</pre>

* Issue 1 - If I run `runme run --all --skip-prompts --category solution-2 --dry-run` I got only first command in markdown document "processed":

  ```
  #!/opt/homebrew/bin/bash

  // run in "/tmp"

  set -e -o pipefail
  echo "[1] Install command in $PWD"
  ```

  -> Second command `[2] Install second command` is skipped / ignored ???

* Issue 2 - The `runme run --all --skip-prompts --category delete-solution --dry-run` is not working at all and `delete-solution` category is not "recognized":
  ```
  could not execute command: No tasks to execute with the category provided
  ```

Maybe I'm missing something, because I didn't look at runme for quite a long time, but it seems like the feature is buggy.

Thank you for looking at it...
