### ISSUE TITLE
tsnode with config?

### ISSUE THREAD

**Issue by archywillhe** [stateful/runme#370]
for example I want to do:

```
ts-node --project ./tsconfig.tsnode.json --transpile-only
```

how do I configure to always pass the remaining para to ts-node?

**Comment by sourishkrout** [comment]
Hey @archywillhe, now that Runme v2 is out, you should be able to specify all the flags inside the interpreter section. Please let me know if that works for you. Here's an example of the `--transpile-only` flag:

<img width="2246" alt="image" src="https://github.com/stateful/runme/assets/250527/9e9ddfc6-dec0-4dac-9f5d-be334faa78a8">

**Comment by sourishkrout** [comment]
I am closing for now. Feel free to reopen if the issue persists.
