### ISSUE TITLE
Docker documentation

### ISSUE THREAD

**Issue by accforgithubtest** [stateful/runme#371]
Would be great to have an official image published to dockerhub. Given the docker files already exist, should be possible to do this via github actions ?

**Comment by christian-bromann** [comment]
Hey @accforgithubtest 👋 

we publish our container on Dockerhub: https://hub.docker.com/r/statefulhq/runme
or are you looking for something else?

**Comment by accforgithubtest** [comment]
@christian-bromann thanks ! thats what I was looking for.

I was looking at https://docs.runme.dev/install, and did not see any docker install options mentioned there.

**Comment by christian-bromann** [comment]
Great feedback, I will take a stab at it and let you review.

**Comment by christian-bromann** [comment]
@accforgithubtest could you check if this little enhancement would work for you: https://docs-runme-c27mzlgbe-stateful.vercel.app/install#runme-with-docker? Are you expecting more docs around it? If so what in particular?

**Comment by accforgithubtest** [comment]
I just tried out with a sample docker compose file, however encountering an error in the logs -
`no named code blocks, consider adding flag --allow-unnamed`. 
No other logs are available.

Here is the compose file -
```
runme:
    image: statefulhq/runme:latest
    container_name: runme
    restart: always
    volumes:
      - ${pwd}:/home/project
    ports:
      - 80
```

This is running behind a reverse proxy, I dont think that is causing any complexities here as other services are running fine behind a proxy.

**Comment by accforgithubtest** [comment]
I can see from documentation that there are few flags that could be passed, Can any of them be passed as environment variables ?
```
allow-unknown 
background
filename
chdir
```

**Comment by accforgithubtest** [comment]
after creating a sample Readme.md in the location mapped to /home/project, I see another line in the log, but the container still exits and I cannot access runme via web UI
```
no named code blocks, consider adding flag --allow-unnamed
add reader to epoll interest list
```

**Comment by christian-bromann** [comment]
@accforgithubtest I am not sure why you would like to use Runme within a Docker compose context. If you are interested to use the CLI I would just use package installer. Can you explain a little bit how you like to use Runme here?

**Comment by accforgithubtest** [comment]
hi @christian-bromann - I have few markdown files that are basically instructions to learn basic linux commands, installing software on linux, etc - basically notes of a simple linux desktop setup. 

When I came across RunMe, I am trying to use the existing markdown files to start with, by mapping a docker volume to my existing markdown notes folder. and trying to run RunMe using docker compose.

In terms of why I am trying to run this in docker instead of installing standalone application - I prefer having applications running in docker containers as I am looking to self host a bunch of applications for my family. 

And I think application  like RunMe might be a great addition to run via docker on a selfhosted set up because it give me ability to share them across. I understand that running the commands will be on the "host" and hence a docker version will not let you run commands on loacl, however this could also be useful to serve as guide to run something on the docker containers then try it on local machines.

Hope that makes sense.

I am still seeing the above mentioned issue and my set up is pretty basic right now - so I am wondering if RunMe really works in a containerized environment ?

**Comment by christian-bromann** [comment]
It does, you can run:
```sh
docker pull statefulhq/runme:latest
docker run -it --volume $(pwd):/home/project statefulhq/runme ls
```
and it should work with Docker. I also was able to create this compose file to run it:

```
services:
  runme:
    image: statefulhq/runme:latest
    container_name: runme
    command: run runThis
    volumes:
      - type: bind
        source: .
        target: /home/project
```

**Comment by admc** [comment]
@accforgithubtest - just following up here, were you able to get what you needed? Feel free to join us on Discord for a real-time convo if that would help.

**Comment by accforgithubtest** [comment]
Thanks for the follow up - I couldnt manage to resolve the above issue I mentioned, so not proceeding with a docker set up.

In the mean time, I am just using the VS Code extension for now, so all good for now.

**Comment by sourishkrout** [comment]
> Thanks for the follow up - I couldnt manage to resolve the above issue I mentioned, so not proceeding with a docker set up.
> 
> In the mean time, I am just using the VS Code extension for now, so all good for now.

Thanks for the persistence! Any chance you could share markdown file you've been using? Would love to resolve this for you and for the benefits of others trying to do the same.
