### ISSUE TITLE
Feedback: it didn't find my root INSTALL.md but subfolders' xyz.md ?!

### ISSUE THREAD

**Issue by kopeboy** [stateful/runme#374]
Runme (or runme tui) was suggesting a myriad of commands from xyz_blabla.md (ie. not only README.md) in typescript/node apps down various folders, but not the top level INSTALL.MD

**Comment by admc** [comment]
Thanks for the feedback @kopeboy.

We have the concept of named cells, and assume that if those are what exist that they are what folks are actually looking for. Any chance you could try: `runme ls --allow-unnamed` and let us know if you see what you're looking for there? Similarly `runme --allow-unnamed` should show all the commands in the TUI.

Also if you are willing to share the contents of INSTALL.md that would help.

We're on Discord if you have any interest in real-time convo! https://discord.gg/runme

**Comment by sourishkrout** [comment]
Hi @kopeboy! Checking in. Did @admc's comments help you? And if not, would you be willing to share your `INSTALL.md` with us? We can do it via email or discord private message if you'd rather not share it on a public channel.

**Comment by joseeantonior** [comment]
Hey @kopeboy,

As we haven't heard from you in a bit, we'll go ahead and close this issue. However, if you continue to have issues, please provide the details requested above and reopen this issue.

Thanks!
