### ISSUE TITLE
Publish to open-vsx.org

### ISSUE THREAD

**Issue by accforgithubtest** [stateful/runme#376]
Pls publish the vscode plugin to [OpenVSX](https://open-vsx.org/), so users of OSS versions / vscode forks can also use runme.

This is a issue discussing the relavant background, and the approach taken by many other extensions can be navigated to using the issue references for other plugins.

https://github.com/microsoft/vscode/issues/31168

**Comment by christian-bromann** [comment]
@accforgithubtest thanks for raising the issue!

We have it published on OpenVSX: https://open-vsx.org/extension/stateful/runme or am I missing something?

**Comment by accforgithubtest** [comment]
Yes, Was able to install from OpenVSX when I tried again, not sure why it kept saying not found during my earlier attempts. Thanks for the quick response. Closing this as a non-issue.
