### ISSUE TITLE
Feature request: commands output to be captured to log file

### ISSUE THREAD

**Issue by serafin-tech** [stateful/runme#400]
Please develop feature for commands' output to be captured to log file, ideally such a log should be shipped to logging endpoint to be protected from deletion.

This is required in my use case to ensure traceability of commands run by operator and to eliminate repeatable command's running. Log shipping may be achieved by some telemetry collector for logs, unless there is control over the place log is being written.
Also such a feature should help securing commands output but not sending this output to 3rd party service (as it may contain sensitive data).

feature discussed during SRECon23 in Dublin

**Comment by sourishkrout** [comment]
Thanks for filing the feature request @serafin-tech! I have taken notes of our conversation at SRECon 2023 in Dublin. Will circle back with a plan shortly.

**Comment by serafin-tech** [comment]
Hi @sourishkrout 

sorry for long response time

re 1. it really depends on the use-case, but given the fact I'd like to protect from repetitive command executions I would save history of all runs. On the other hand I can imagine scenario that one is interested only in recent output, so maybe a feature-flag for that might be solution.

re 2. I would say having the output in markdown document would be one of the solutions. One can attach it to the ticket/change control as a proof of work. What might be needed in such case is some protection from overwriting vanilla runbook with copy containing output of the commands. Probably suggestion to write it under new name would be enough.

re 3. That's a good question. In the use-case I'm thinking about opening IDE with runbook would mean opening new session. Probably retaining the session between two openings of runbook in IDE would be valid but I wouldn't invest time in it now and keep it as separate feature.

re 4. IMO critical are timestamps from executions. But what might be good to record IMO is sha of last commit for the runbook, to record the version used by operator. Of course it will no guarantee runbook had not been modified but at least give a hint if operator used recent version while dong the job.

I wouldn't add more features now not to over-complicate your work. I'd really like to see outcome to start experimenting.

And again - appreciate your work on the tool

**Comment by sourishkrout** [comment]
@serafin-tech I agree that starting simple and providing feedback iteratively is likely the better path than trying to anticipate all the corner cases. Thank you for the feedback; this will help us get started on the first version for review.

will keep you posted on the progress.

**Comment by sourishkrout** [comment]
Here's some work in progress, @serafin-tech. However, instead of writing the output (plus runtime info) back to the original markdown file in an initial version, Runme will write a full copy per session (enabled via feature flag). Shooting for an opt-in release in the next 1-2 weeks.

<img width="2560" alt="image" src="https://github.com/stateful/runme/assets/250527/4865b915-f8c0-4812-a0a2-36b37efebabe">

[stdio.md](https://github.com/stateful/runme/files/13257991/stdio.md)
[stdio-cl3dopjjtojcs1tcq150.md](https://github.com/stateful/runme/files/13257992/stdio-cl3dopjjtojcs1tcq150.md)

**Comment by sourishkrout** [comment]
We are making good headway. Remaining step to a first version is to write full copy of the markdown/notebook file including captured outputs to a separate file.

**Comment by sourishkrout** [comment]
We just shipped Runme v2.1.4 with a feature-flagged experiment to save Runme notebook outputs to a separate session file.

It's easy to turn on in Settings (CMD + , on Mac) under `@ext:stateful.runme runme.experiments.outputPersistence`. Check the box and restart.

Here's an example. Noticed the "Session Outputs" button which will open the corresponding file to the side in markdown preview.

![Image](https://github.com/stateful/runme/assets/250527/dd7e42af-ff6e-49d6-8b79-d604b590d0aa)

**Comment by serafin-tech** [comment]
Hi @sourishkrout,

I've tested this new feature and it looks very promising. Output is saved and secured as you promised.

re your comments:

- The "session file with output" may be easily reused to restore previous session. The challenge may be environment variables, but I would leave solving it for runbook developer as for now. Additional data in frontmatter may be helpful here,
- Saving output needs to be reviewed. Now I see the save is done when next command block is being executed - this is not acceptable. If this is to be used for execution tracking save have to be done immediately after block execution is completed. I discovered this gap when I lost one output...

And thanks a lot for Your work on this software

Ser@fin

**Comment by serafin-tech** [comment]
@sourishkrout,

I noticed one more thing - in my test runbook I have a command which does not emit any output (simple `curl`) thus the execution capture is empty. Would you be able to record process return code in such cases?

TIA

**Comment by sourishkrout** [comment]
> @sourishkrout,
> 
> I noticed one more thing - in my test runbook I have a command which does not emit any output (simple `curl`) thus the execution capture is empty. Would you be able to record process return code in such cases?
> 
> TIA

I can take a look into it. Do you have an example shell snippet for such a curl that doesn’t produce an output (just in case). I’ll try reproducing it tmrw and will get back regarding your other comments.

**Comment by serafin-tech** [comment]
> > @sourishkrout,
> > I noticed one more thing - in my test runbook I have a command which does not emit any output (simple `curl`) thus the execution capture is empty. Would you be able to record process return code in such cases?
> > TIA
> 
> I can take a look into it. Do you have an example shell snippet for such a curl that doesn’t produce an output (just in case). I’ll try reproducing it tmrw and will get back regarding your other comments.

nothing sophisticated: `curl -o file.name https://url.to.be/downloaded`

**Comment by sourishkrout** [comment]
> > > @sourishkrout,
> > > I noticed one more thing - in my test runbook I have a command which does not emit any output (simple `curl`) thus the execution capture is empty. Would you be able to record process return code in such cases?
> > > TIA
> > 
> > 
> > I can take a look into it. Do you have an example shell snippet for such a curl that doesn’t produce an output (just in case). I’ll try reproducing it tmrw and will get back regarding your other comments.
> 
> nothing sophisticated: `curl -s -o file.name https://url.to.be/downloaded`

Repro'd it adding the slient flag `-s`. Fixed the issue. Runme will now [write empty outputs](https://github.com/stateful/runme/pull/449) as long as they have a valid "execution summary". We get this out in the next release in the next few days, @serafin-tech.

**Comment by sourishkrout** [comment]
Shipped: https://runme.dev/blog/runme-v3-pipeline-logs-and-artifacts
