### ISSUE TITLE
[internal/project] `DocumentPath` in tasks is consistent

### ISSUE THREAD

**Issue by adambabik** [stateful/runme#467]
Recently, we discovered [some inconsistencies](https://github.com/stateful/runme/pull/465#discussion_r1442169829) when observing paths returned from `runme ls` and `runme tui`, and more precisely from `Project.Load()` from the `internal/project` package. 

The special case is when the project is bootstrapped by walking the directory upwards. However, the same thing happens if `--project` is an absolute path.

There are two options:
- Always return absolute paths and do post processing by the caller.
- Always return relative paths; relative to the `Project.Root()`.

cc @sourishkrout

**Comment by sourishkrout** [comment]
> * Always return absolute paths and do post processing by the caller.

let's do this please. thank you @adambabik!
