### ISSUE TITLE
Update Twitter icon in website of Stateful

### ISSUE THREAD

**Issue by Ayush9026** [stateful/runme#485]
Update Twitter icon with new one that is 'X'. Marked in Screenshot below.

![Sateful](https://github.com/stateful/runme/assets/114745463/43877266-a417-4746-bc20-ab0f30a3c1a2)

**Comment by sourishkrout** [comment]
Thanks for reporting this @Ayush9026! @admc will get this fixed.

**Comment by admc** [comment]
Thanks @Ayush9026 - all set.
