### ISSUE TITLE
I can not save a file 'as' in vscode

### ISSUE THREAD

**Issue by Luxcium** [stateful/runme#489]
I have this error message: 
Failed to save 'typescript-function-overloads-testing.formal.md': File name file:///projects/monorepo-one/prompts/API/GPTs/typescript-assistant/typescript-function-overloads-testing.formal.md.txt is not supported by Runme Infra Notebooks.

Please make sure the file name matches following patterns:
*.md, *.mdx, *.mdi, *.mdr, *.run, *.runme

![Screenshot_20240204_003523](https://github.com/stateful/runme/assets/42672814/0f559fa1-135f-4f58-b220-a2ccf42f0f3a)

you should not stop the user to save a file in an other format to opt out of your app (extension) I am not able to select which files are covered or not then I am also unable to save as .txt

**Comment by sourishkrout** [comment]
Thanks for reporting this @Luxcium. We will take a look and respond shortly.
