### ISSUE TITLE
Problem parsing with lists containing code blocks

### ISSUE THREAD

**Issue by christian-bromann** [stateful/runme#49]
The following example of markdown is not rendered correctly:

    ## Running
    
    ### In Minikube
    
    Deploy the application to Minikube using the Linkerd2 service mesh.
    
    1. Install the `linkerd` CLI
    
        ```bash
        curl https://run.linkerd.io/install | sh
        ```
    
    1. Install Linkerd2
    
        ```bash
        linkerd install | kubectl apply -f -
        ```

    1. View the dashboard!
    
        ```bash
        linkerd dashboard
        ```
    
    1. Inject, Deploy, and Enjoy
    
        ```bash
        kubectl kustomize kustomize/deployment | \
            linkerd inject - | \
            kubectl apply -f -
        ```
    
    1. Use the app!
    
        ```bash
        minikube -n emojivoto service web-svc
        ```

It should be rendered like this:

### In Minikube

Deploy the application to Minikube using the Linkerd2 service mesh.

1. Install the `linkerd` CLI

    ```bash
    curl https://run.linkerd.io/install | sh
    ```

1. Install Linkerd2

    ```bash
    linkerd install | kubectl apply -f -
    ```

1. View the dashboard!

    ```bash
    linkerd dashboard
    ```

1. Inject, Deploy, and Enjoy

    ```bash
    kubectl kustomize kustomize/deployment | \
        linkerd inject - | \
        kubectl apply -f -
    ```

1. Use the app!

    ```bash
    minikube -n emojivoto service web-svc
    ```

But gets rendered like this:

<img width="486" alt="Screenshot 2022-10-27 at 10 38 34" src="https://user-images.githubusercontent.com/731337/198360319-b03c12ca-3a65-42c8-8b49-876c22828514.png">

**Comment by adambabik** [comment]
@christian-bromann this is very interesting case. Another one, less popular, is a code block within a block quote.

Have you seen https://github.com/microsoft/vscode-markdown-notebook? It seems to be doing exactly what we need and the output looks almost right. The order is not preserved, all list items starts with `1.` and it does not handle the case with a block quote. The algorithm is pretty trivial though.

I am working on something a bit more advanced which will move code blocks up to the top level under the root node while preserve the affected blocks.

**Comment by adambabik** [comment]
I implemented the case of nested code blocks in https://github.com/stateful/runme/commit/86322f112d2516e4ea66831e78343717ffc8b088. If it takes me longer than anticipated to merge `new-wasm-api`, then I will try to cherry pick that commit into `main`.
