### ISSUE TITLE
Distribute runme as npm module `runme`

### ISSUE THREAD

**Issue by sourishkrout** [stateful/runme#51]
To get ahead of a plan to use the CLI to run commands inside of `vscode-runme`, let's distribute the gobinaries and wasm builds as NPM package. This will also allow to transparently manage the dependencies between `vscode-runme` <> `runme`. I remember having seen a way to repackage a gobinary as module elegantly.

Ideally we could pick up on the existing tag based publication workflows: https://github.com/stateful/runme/actions/workflows/release.yml

@admc should be able to add you to the `runme` npm module name which we own.

**Comment by sourishkrout** [comment]
As mentioned, this module was meant to be a binary distribution for the WASM build and ideally the go binary for the respective platforms. The WASM build is a library subset which won't do much when executed directly.

Lemme know if there are any questions @christian-bromann.

**Comment by christian-bromann** [comment]
Please review: https://github.com/stateful/runmejs

I wanted to make it support Node.js , Deno and browser environments but this doesn't work without a more complex build pipeline. I would punt on that unless it is super important. So far it does what you mention: downloads the go binary based on the platform and allows to run it as CLI (basically offering a way to install it through NPM).

**Comment by sourishkrout** [comment]
> Please review: https://github.com/stateful/runmejs
> 
> I wanted to make it support Node.js , Deno and browser environments but this doesn't work without a more complex build pipeline. I would punt on that unless it is super important. So far it does what you mention: downloads the go binary based on the platform and allows to run it as CLI (basically offering a way to install it through NPM).

I installed it locally and it looks like it checks the boxes on all the requirements. Running/importing the WASM is somewhat extracurricular for now. Once we riff on architecture boundaries perhaps it's something we want to revisit later.

We can probably close out this issue. One more question: Is there a straightforward way to sync `runme` and `runmejs` releases? Like one workflow triggering another? Is that too brittle?

**Comment by christian-bromann** [comment]
> Like one workflow triggering another? Is that too brittle?

Not at all. Question: do we want to tight the runme CLI version to the NPM package version?
