### ISSUE TITLE
Bug: 'go install' command installs older version (v1.8.2) Instead of latest one

### ISSUE THREAD

**Issue by pastuxso** [stateful/runme#514]
When installing runme using the command `go install github.com/stateful/runme@latest`, the installation process only installs version v1.8.2. However, it should install the latest available version, preferably v3.0.2 or later.

**Comment by adambabik** [comment]
Likely https://github.com/stateful/runme/blob/main/go.mod#L1 should be changed to `module github.com/stateful/runme/v3`.

**Comment by pastuxso** [comment]
The issue is still happening.


![Image](https://github.com/stateful/runme/assets/43882/c4914bab-806c-4cd2-b45e-0b018e842068)

**Comment by pastuxso** [comment]
@sourishkrout I understand :see_no_evil: what's happening, for major versions we need to use the /vX in the path, so @edeediong the docs should be updated considering the version.

![image](https://github.com/stateful/runme/assets/43882/57f3b68c-13be-43de-a3ce-c53c1d9361b0)

**Comment by sourishkrout** [comment]
Well, it should just work with `@latest` now ever since we merged and released https://github.com/stateful/runme/pull/517
