### ISSUE TITLE
Reconcile shell script prep functions

### ISSUE THREAD

**Issue by sourishkrout** [stateful/runme#57]
The preparation of the script is platform specific:

https://github.com/stateful/vscode-runme/blob/a61f235ab9c97d0ae57135cddcb2270fd4aae162/src/extension/utils.ts#L51-L73

The `prepareScript` function is currently agnostic and likely run into issues on Windows:

https://github.com/stateful/runme/blob/4b2fce8ddfcbab8aeda13e938048dd85edc4de59/web/main_js.go#L124-L132

Windows issue for more context: https://github.com/stateful/vscode-runme/issues/20 (never fully figure out if this is a bash vs shell problem or Windows 🤷‍♀️)

**Comment by adambabik** [comment]
With the current approach, the deserialization process returns cells which content is valid code to be executed. We don't expose `prepareScript` anymore.
