### ISSUE TITLE
Support using Foyle's AI capabilities as a plugin

### ISSUE THREAD

**Issue by jlewi** [stateful/runme#574]
Per the discussion in discord; we'd like to experiment with integrating RunMe with [Foyle's AI](https://foyle.io/) capabilities. Foyle aims to be a DevOps copilot. One of the key problems its tackling is trying to train an AI copilot to be an expert in your infrastructure. Foyle relies on a notebook like experience to collect implicit human feedback which is used to train the AI ([blog post](https://foyle.io/docs/blog/learning/)). Like RunMe, Foyle is also built using VSCode Notebooks. RunMe is far more mature and has more features than Foyle. So it likely makes sense to reuse RunMe as Foyle's notebook rather than rebuilding a separate stack.

Towards that end, this issue is tracking the minimal implementation to get RunMe to support calling out to Foyle and surfacing the results. The current thinking is they would be two separate extensions to start with and RunMe would use gRPC to communicate with Foyle. A more detailed design is provided in [Foyle Tech Note 004](https://github.com/jlewi/foyle/blob/main/tech_notes/tn004_runme.md).

 The first step is designing a shared gRPC service to allow the services to communicate; #573 

- [x] Create a minimal runme code to generate completions using foyle (#1356)
- [x] Ensure Runme logs data necessary for retraining Foyle
- [ ] Related to jlewi/foyle#110

**Comment by jlewi** [comment]
Here's a more detailed look at what we need to do for logging

# Gaps In Current RunMe Logging

Here are the current limitations of logging in RunMe for the purposes of supporting Foyle retraining

* Server logging isn't always enabled when using VSCode
* When server logs are enabled, server logs aren't persisted to files; they are echoed to an output terminal in VSCode
   * This means they are ephemeral and aren't easily accessible by Foyle for retraining
* Server Logs don't record the actual executed command at info level
  * request is logged at debug level [here](https://github.com/stateful/runme/blob/3d637c0238b8bd6b465118181efdbadd054fe3b3/internal/runner/service.go#L219)
  * However, I don't think it would be logged using the JSON serialization format of the proto which would make deserializing it difficult
    * Per [StackOverflow](https://stackoverflow.com/questions/68411821/correctly-log-protobuf-messages-as-unescaped-json-with-zap-logger)
      it won't be seralized as the proto JSON format

# Proposed Changes to RunMe Code Base

## Server Changes

* Server should setup a second logger to always log to a JSON file 
   * We can use a tee logger as in [Foyle](https://github.com/jlewi/foyle/blob/dca28ab8423d48c50ca62be3dedd451fa1c15c45/app/pkg/application/app.go#L173) to create a logger that sends messages to the console and to the JSON file

* The logs should be stored in `${CONFIGDIR}/logs`

* Add a command line flag to the [serve command](https://github.com/stateful/runme/blob/3d637c0238b8bd6b465118181efdbadd054fe3b3/internal/cmd/server.go#L135) to enable Foyle logs

* Add a [configDir flag](https://github.com/stateful/runme/blob/3d637c0238b8bd6b465118181efdbadd054fe3b3/internal/cmd/api_common.go#L68) to the [serve command](https://github.com/stateful/runme/blob/3d637c0238b8bd6b465118181efdbadd054fe3b3/internal/cmd/server.go#L135) 

* [Execute Logger](https://github.com/stateful/runme/blob/3d637c0238b8bd6b465118181efdbadd054fe3b3/internal/runner/service.go#L219) should be keyed by [known_id](https://github.com/stateful/runme/blob/3d637c0238b8bd6b465118181efdbadd054fe3b3/pkg/api/proto/runme/runner/v1/runner.proto#L186) and [known_name](https://github.com/stateful/runme/blob/3d637c0238b8bd6b465118181efdbadd054fe3b3/pkg/api/proto/runme/runner/v1/runner.proto#L192) is present

*  We need to log the Execute  request at info level in JSON format [StackOverflow](https://stackoverflow.com/questions/68411821/correctly-log-protobuf-messages-as-unescaped-json-with-zap-logger) 
   * An issue here is how to log it in proto JSON format
   * The simplest thing to do is to just add code to serialize the request to JSON and then log the result
   * The alternative is to to use the  proto plugin [go-proto-zap-marshaler](https://github.com/kazegusuri/go-proto-zap-marshaler) to auto generate LogMarshalObject methods for all protos
      * That only makes sense if there's going to be widespread logging of protos in JSON format. Since we only need to update a single log message right now I don't think its worth introducing it as part of this change

## vscode-runme Changes

I think the main changes we'd need to make to RunMe's vscode extension is to plumb through the server changes

* We should introduce a Foyle experiments flag to enable Foyle
* Update [start](https://github.com/stateful/vscode-runme/blob/f6299b33a168d59b01e5df4937fc942e9039f0bf/src/extension/server/runmeServer.ts#L229) in runmeServer.ts to pass along the appropriate command line flags if the Foyle experiment is enabled

@sourishkrout Could you PTAL and let me know if this looks good or if you have any suggestions before I get started on implementing the changes?

**Comment by sourishkrout** [comment]
> @sourishkrout Could you PTAL and let me know if this looks good or if you have any suggestions before I get started on implementing the changes?

Overall this looks good to me. One thing I'm wondering 🤔 is how do we make it clear that logging is no longer exclusively for "human consumption" (troubleshooting, debugging, etc)? As far as I understand your proposal Foyle's training will be based on the logs being stable and machine-readable, no @jlewi?

**Comment by sourishkrout** [comment]
👍 @jlewi. Don't see a problem in changing logging in Runme to suit the needs here.

> This means if someone removes or edits the above log line they could break certain functionality; this is rather unexpected for most developers. I don't have good solutions for that. In principle, we could use a combination of linters and unittests to catch those breakages.

This is primarily what I'd like to guard against. I think a combo of unit tests and perhaps we can even name the `logger.(...)` something like `learningLogs.(...)` or something that makes developers think twice. In any case, unit tests are usually the best guard in this scenario to maintain a "contract".

**Comment by sourishkrout** [comment]
> * An issue here is how to log it in proto JSON format
> * The simplest thing to do is to just add code to serialize the request to JSON and then log the result
> * The alternative is to to use the  proto plugin [go-proto-zap-marshaler](https://github.com/kazegusuri/go-proto-zap-marshaler) to auto generate LogMarshalObject methods for all protos
>   
>   * That only makes sense if there's going to be widespread logging of protos in JSON format. Since we only need to update a single log message right now I don't think its worth introducing it as part of this change

I suggest going the simple route first and see how far that'll get us.

**Comment by jlewi** [comment]
After #585 ; the only remaining change on the RunMe side is to add a vscode flag to enable Foyle which would launch the RunMe server with the flags to enable logging.  That's only a blocker to being able to train off of RunMe data but using Foyle should still work even without that.

I believe Foyle should be available in RunMe vscode as soon as 
https://github.com/stateful/vscode-runme/pull/1356
Lands in a release.
It looks like it just missed the 3.5.5 release
https://github.com/stateful/vscode-runme/releases/tag/3.5.5

**Comment by jlewi** [comment]
* I released Foyle 0.0.11 https://github.com/jlewi/foyle/releases/tag/v0.0.11 which should have all the code to support RunMe
* I've updated Foyles Docs https://foyle.io/docs/getting-started/
* RunMe 3.5.7 https://github.com/stateful/vscode-runme/releases/tag/3.5.7 was released earlier today
  * This has all the code to support Foyle but it has bug https://github.com/jlewi/foyle/issues/125
  * https://github.com/stateful/vscode-runme/pull/1389 has the fix

**Comment by jlewi** [comment]
Woo Hoo! Thanks @sourishkrout
