### ISSUE TITLE
Internal failure executing runner: failed program lookup "deno run"

### ISSUE THREAD

**Issue by sourishkrout** [stateful/runme#595]
Instead of looking up `deno run` it should attempt a look up against `deno` and prepend `run` to the args stack.

https://github.com/stateful/runme/blob/main/internal/command/command.go#L102-L116

This works in runner v1. Let's be sure to add a test case.

**Comment by adambabik** [comment]
Good point! It was done in the following way in runnerv1: https://github.com/stateful/runme/blob/56a77e8cde086ed1be7e118bc555b173d6543f5f/internal/runner/command.go#L660-L672

**Comment by sourishkrout** [comment]
> Good point! It was done in the following way in runnerv1:
> 

That works but also open to alternatives if you have something else in mind 👍.

**Comment by adambabik** [comment]
@sourishkrout to confirm the use case, does `deno run` come from the client in `runme.runner.v2alpha1.ProgramConfig.program_name`?

**Comment by sourishkrout** [comment]
> @sourishkrout to confirm the use case, does `deno run` come from the client in `runme.runner.v2alpha1.ProgramConfig.program_name`?

Just saw this now... Yes, I believe that's what's being set plus the `CommandMode=File`.
