### ISSUE TITLE
Saved output replaces valid characters with asterisks

### ISSUE THREAD

**Issue by jlewi** [stateful/runme#611]
I'm using RunMe in vscode. I turn on Auto-Save. In the markdown saving the output, the output of shell commands has "*".

Here's a gist I created from the output markdown
https://gist.github.com/jlewi/0d4d6b346d6054821492de505fd010e7

There shouldn't be any asterisks.

The actual kubectl output is 

```
NAME                                 STATUS   ROLES    AGE   VERSION
gk3-dev-nap-j09tzqm6-9096877b-v5m4   Ready    <none>   22m   v1.28.9-gke.1000000
gk3-dev-pool-1-6feb3810-b9l6         Ready    <none>   25m   v1.28.9-gke.1000000
```

**Comment by sourishkrout** [comment]
@jlewi have you tried the "Unmask" button in the notebook toolbar yet? We're actually currently updating our docs to be more clear about this.

<img width="1144" alt="image" src="https://github.com/stateful/runme/assets/250527/6b630432-dad3-4ec3-8bce-d13770c5d238">

**Comment by sourishkrout** [comment]
Also more details are available in this blog post too: https://runme.dev/blog/runme-gist

**Comment by jlewi** [comment]
That was it. Thank you!

**Comment by sourishkrout** [comment]
Just for reference. The docs are here: https://docs.runme.dev/configuration/runme-gist.
