### ISSUE TITLE
runme attempts to access unreadable files or directories

### ISSUE THREAD

**Issue by pastuxso** [stateful/runme#645]
I encountered an issue where the **runme** does not skip unreadable files or directories during processing, leading to a **permission denied** error. This behavior occurs even when the files or directories should be ignored using the **--ignore-pattern** flag.

Issue reported on [Discord](https://discord.com/channels/1102639988832735374/1102639989700968583/1269389054399479880) 

PR to replicate the issue: https://github.com/stateful/runme/pull/646 https://github.com/stateful/runme/actions/runs/10252402970/job/28362697530?pr=646#step:7:33

**Comment by adambabik** [comment]
It looks like we don't handle `os.ErrPermission` https://github.com/stateful/runme/blob/0cf2e624ba20f8b6cf91eb586f75148e9b682cf2/pkg/project/project.go#L367-L370.

This type of error should be handled separately, and if the path is ignored, it should be skipped. @pastuxso would you like to tackle this?

**Comment by pastuxso** [comment]
@adambabik, I could fix it. Thank you for your review. 👍🏻
