### ISSUE TITLE
First past WASM integration

### ISSUE THREAD

**Issue by sourishkrout** [stateful/runme#68]
- New lines trailing every code block
- Markdown triple backticks included in `value` of code blocks
- Byte arrays vs strings as return value of serializer: let's be sure unicode is being preserved
- Sebastian will tinker with thread-safety of de-/serialization to better understand exposure

**Comment by adambabik** [comment]
@sourishkrout I think it's a good time to also move functions from the extension codebase like language detection. Any objections?

**Comment by sourishkrout** [comment]
> @sourishkrout I think it's a good time to also move functions from the extension codebase like language detection. Any objections?

Not at all. For `guesslang`: I had this working in https://github.com/stateful/runme/tree/seb/ml - there's some native linking for x-platform builds to be figured out (hopefully goreleaser makes this easy) since tensorflow is linked via the C/C++ interface.

**Comment by adambabik** [comment]
> Byte arrays vs strings as return value of serializer: let's be sure unicode is being preserved

This should be already covered in https://github.com/stateful/runme/pull/71. I also added detection for LF (unix) vs CRLF (windows).

**Comment by adambabik** [comment]
> Sebastian will tinker with thread-safety of de-/serialization to better understand exposure

This is irrelevant now as both `Runme.serialize()` and `Runme.deserialize()` are side-effect-free.

**Comment by adambabik** [comment]
Closing as all points are fulfilled in the `main` branch.
