### ISSUE TITLE
Env prompt: Escape sequences

### ISSUE THREAD

**Issue by max06** [stateful/runme#709]
Hello there!

Just an optical inconvenience...

Given following snippet:

```bash
export TYPE=[Guest type \(hyperv,proxmox,openstack\)]
export TARGET=[IP of waiting server]
```

Result:
![image](https://github.com/user-attachments/assets/2b9cf5c1-7a6a-40bc-80f7-751f93385b60)

The backslash-escape in front of the parentheses is required in bash. Runme should probably parse, sanitize and display these properly.

**Comment by sourishkrout** [comment]
Thanks for reporting, @max06! We will get that fixed in the following weeks.

**Comment by sourishkrout** [comment]
The cosmetic fix will go out with the next stable release, @max06.

**Comment by max06** [comment]
Lovely, thanks a lot!
