### ISSUE TITLE
Variable substitution fails in heredoc

### ISSUE THREAD

**Issue by seldomU** [stateful/runme#710]
In this script the variable does not get substituted when running as notebook cell, but it does when running as a .sh file.

```bash
Foo="bar"
cat << EOF
$Foo
EOF
```

Adding a character in front of it helps:
```bash
Foo="bar"
cat << EOF
a$Foo
EOF
```

**Comment by sourishkrout** [comment]
This will be fixed in the next point release in the next few days, @seldomU.
