### ISSUE TITLE
The enumerated list is being turned into a series of 1s

### ISSUE THREAD

**Issue by sourishkrout** [stateful/runme#78]
tested with https://github.com/stateful/baldaquin/blob/main/README.md (internal repo). The enumerated list is being turned into a series of 1s... I know this might not be trivial but I wonder if it's possible to parse them as is (text) vs an enumerated list?

_Originally posted by @sourishkrout in https://github.com/stateful/runme/pull/71#pullrequestreview-1209125271_

**Comment by sourishkrout** [comment]
Tested this again according to https://github.com/stateful/runme/pull/71#issuecomment-1342546996. Still getting a series of 1s. Anything I'm missing?

**Comment by adambabik** [comment]
@sourishkrout which version have you tried? Please print it with `runme --version`.

````
➜ ./runme --version
runme version stateful 0.4.0-rc.0-4-geef463c-eef463c (eef463cd8aeb5f101badceb5524ae9249e7ec54c) on 2022-12-12T11:25:54Z

➜ ./runme fmt --flatten "https://raw.githubusercontent.com/stateful/baldaquin/main/README.md?token=REDACTED"
[...]

## Development

1. Ensure you have [dev](https://github.com/stateful/dev) setup and running

2. Install MacOS dependencies

```sh
brew bundle --no-lock
```

3. Setup pre-commit

```sh
pre-commit install
```

[...]
````

In the extension it also looks correct:

![Screenshot 2022-12-12 at 12 29 41](https://user-images.githubusercontent.com/277870/207034465-9e1f644c-f8b2-41dc-b677-b34e67367033.png)

**Comment by sourishkrout** [comment]
Weird. This is what I'm using: `runme version stateful
0.4.0-rc.0-1-gdf03678-df03678 (df0367895dbb401dbed554bc90e2f673c025f3d7) on
2022-12-12T13:47:46Z`

**Comment by sourishkrout** [comment]
OK, you were right 🤦 . Sorry, turns out the series of 1's was in the underlying file.
