### ISSUE TITLE
Code block name in metadata

### ISSUE THREAD

**Issue by sourishkrout** [stateful/runme#83]
1. Let's include `name` directly into the metadata if it was parsed from a respective markdown file's code block.
2. Additionally, let's add `runme.dev/name` (including on-the-fly generated ones) to `runme.dev/*` special attributes (ephmeral) which won't be subject so serialization for all blocks, including 1.). The `name` is required to be able to call the CLI from the extension.

This will maintain "good" UX where name's are only being serialized if set by the user.

**Comment by sourishkrout** [comment]
@adambabik could you knock this one out please? It's required to restore functionality in the extension.

**Comment by adambabik** [comment]
> Let's include name directly into the metadata if it was parsed from a respective markdown file's code block.

This is the current behaviour.

> Additionally, let's add runme.dev/name (including on-the-fly generated ones) to runme.dev/* special attributes

This is missing. I am preparing a PR.

**Comment by sourishkrout** [comment]
Looking forward to it @adambabik 👍 .
