### ISSUE TITLE
v0.4 release punch list

### ISSUE THREAD

**Issue by sourishkrout** [stateful/runme#85]
In priority order:

- [x] For code block lang normalization: if code block lang is unknown include as CODE (vs MARKUP). However, keep returning MARKUP for explicitly set languages that are not supported (e.g. `py`) 
- [x] Unify supported languages between the ext and CLI (golang is not supported)

Once fixed release as v0.4.

Nice to have:
- [x] Additional new lines after converting to Code->Markdown->Code? Could be my mistake

**Comment by adambabik** [comment]
> For code block lang normalization: if code block lang is unknown include as CODE

Should I keep the `langId` empty or default it to `sh`?

**Comment by sourishkrout** [comment]
Empty please. The guesslang model in the extension will attempt to guess it.

**Comment by adambabik** [comment]
> Additional new lines after converting to Code->Markdown->Code? Could be my mistake

I can't reproduce it. It must have been a typo.

**Comment by sourishkrout** [comment]
https://github.com/stateful/runme/releases/tag/v0.4.0
