### ISSUE TITLE
Frontmatter is not being preserved

### ISSUE THREAD

**Issue by sourishkrout** [stateful/runme#89]
Popular tooling like docusaurus, Jekyll, and Hugo use frontmatter to store metadata. Runme's parser should at the minimum make sure to preserve it.

Related to https://github.com/stateful/runme/issues/88

**Comment by sourishkrout** [comment]
Let's take a look into this soon please @adambabik. I tested with files here: https://github.com/stateful/runme.dev/blob/main/docs/intro.md and it appears we're treating frontmatter like regular markdown.

**Comment by adambabik** [comment]
I did an initial research and Hugo uses the same MD parser as we do but it does not use it for Front Matter. It uses a custom pre-parser which recognizes various formats. It's [documented](https://gohugo.io/content-management/front-matter/).

I will use the same technique.

**Comment by sourishkrout** [comment]
> I did an initial research and Hugo uses the same MD parser as we do but it does not use it for Front Matter. It uses a custom pre-parser which recognizes various formats. It's [documented](https://gohugo.io/content-management/front-matter/).
> 
> I will use the same technique.

Sounds good 👍 . We might want to consider retaining the frontmatter (blob) in a single metadata field across short-term just to make sure it's not being wiped if that's a quicker stop-gap fix. Longer-term it'd be great to have the frontmatter parsed and serializable into its originate format (yaml, json, toml, etc).
